name: housing
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pandas=2.1.1
- scikit-learn=1.3.1
- pydantic=2.7.0
- fastapi[standard]=0.112.0
- requests=2.32.5
- locust=2.34.0
- matplotlib=3.9.4